In [113]:
import numpy as np
from copy import deepcopy
import math

In [114]:
def derivativeOutput(s):
    return derivativeActivation(s)

In [115]:
def derivativeActivation(s):
    return activation(s) * (1 - activation(s)) 

In [116]:
def activation(x):
  return 1 / (1 + math.exp(-x))

In [117]:
def outputf(s):
    return activation(s)

In [118]:
def forwardPropagation(x, weights):
    Xl = np.array(x)
    W = np.array(weights)
    S = []
    X = [x]
    for index, l in enumerate(W):
        wl = np.array(l)
        sl = np.transpose(wl).dot(Xl)
        Xl_before_activation = sl
        if index != len(W) - 1:
            activation_function = np.vectorize(activation)
            Xl = activation_function(Xl_before_activation)
            Xl = np.insert(Xl, 0, 1, axis=0)
        else:
            output_function = np.vectorize(outputf)
            Xl = output_function(Xl_before_activation)
        X.append(Xl)
        S.append(sl)
    np.delete
    return np.array(X), np.array(S)

In [119]:
def backPropagation(X, y_n, s, weights):
    w = deepcopy(weights)
    g = [None] * len(X)
    X = np.array(X)
    for layer, Xl in enumerate(reversed(X)):
        layer = len(X) - layer - 1
        if layer == len(X) - 1:
            delta = 1 * (y_n - Xl[0]) * derivativeOutput(s[-1][0])
            g[layer] = np.array([delta])
        elif layer > 0:
            deltas = []
            for d in range(len(s[layer - 1])):
                derivative = derivativeActivation(s[layer - 1][d])
                sum = 0
                for k, delta in enumerate(g[layer + 1]):
                    sum += (delta * w[layer][d+1][k])
                deltas.append(sum * derivative)
            g[layer] = np.array(deltas)

    g = g[1:]

    to_update_W = w
    for layer, Xl in enumerate(X[:-1]):
        to_update_W[layer] = np.dot(np.array([Xl]).T, np.array([g[layer]]))
    return g, to_update_W

In [120]:
w = [
    [
        [0, 0, 0],
        [-0.88789356, 0.98357215, 0.86408093],
        [0.36358684, -0.10507245, 0.51025131]
    ],
    [
        [0],
        [-0.97729476],
        [-0.89905958],
        [-0.8489134]
    ]
]

In [121]:
x1 = 0
x2 = 0
x = np.array([
    1,
    x1,
    x2
])

In [122]:
y = 0

In [123]:
X, S = forwardPropagation(x, w)

In [124]:
X

array([array([1, 0, 0]), array([1. , 0.5, 0.5, 0.5]), array([0.20381256])],
      dtype=object)

In [125]:
g, err = backPropagation(X, y, S, w)

In [126]:
g

[array([0.00808058, 0.00743371, 0.00701909]), array([-0.03307328])]

In [127]:
err

[array([[0.00808058, 0.00743371, 0.00701909],
        [0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        ]]), array([[-0.03307328],
        [-0.01653664],
        [-0.01653664],
        [-0.01653664]])]

In [128]:
w_u = np.add(w, err)
w_u

array([array([[ 0.00808058,  0.00743371,  0.00701909],
       [-0.88789356,  0.98357215,  0.86408093],
       [ 0.36358684, -0.10507245,  0.51025131]]),
       array([[-0.03307328],
       [-0.9938314 ],
       [-0.91559622],
       [-0.86545004]])], dtype=object)

In [129]:
w = w_u
w

array([array([[ 0.00808058,  0.00743371,  0.00701909],
       [-0.88789356,  0.98357215,  0.86408093],
       [ 0.36358684, -0.10507245,  0.51025131]]),
       array([[-0.03307328],
       [-0.9938314 ],
       [-0.91559622],
       [-0.86545004]])], dtype=object)

In [143]:
for _ in range(100):
    for data in np.array([([1,1,1],0),([1,1,0],1),([1,0,1],1),([1,0,0],0)]):
        x, y = data
        X, S = forwardPropagation(x, w)
        g, err = backPropagation(X, y, S, w)
        w_u = np.add(w, err)
        w = w_u
print('done')

done


In [144]:
w

array([array([[ 2.12375957, -2.21654141, -6.03388906],
       [-5.76384874,  1.29374009,  3.85691272],
       [-5.73255482,  1.23672914,  3.87786245]]),
       array([[ 4.24432187],
       [-7.94192562],
       [-1.58450248],
       [-7.30649963]])], dtype=object)

In [157]:
x1 = 0
x2 = 1
x = np.array([
    1,
    x1,
    x2
])

In [158]:
X, S = forwardPropagation(x, w)

In [159]:
X[-1][-1]

0.9450203645189414