In [1]:
import numpy as np
a = np.zeros(3)
a

array([0., 0., 0.])

In [2]:
type(a)
print(type(a[0]))
a = np.zeros(10)
a

<class 'numpy.float64'>


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
a.shape

(10,)

In [4]:
a.shape = (10,1)
a.shape

(10, 1)

In [5]:
a

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [6]:
a = np.ones(10)
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
a = np.empty(3)
a

array([0., 0., 0.])

In [8]:
a = np.linspace(0,4,5)
a

array([0., 1., 2., 3., 4.])

In [9]:
a = np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
array = [9,8,7,6,5,4,3,2,1]
a = np.array(array)
a

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [11]:
np.random.seed(0)
a = np.random.randint(100,size=20)
a

array([44, 47, 64, 67, 67,  9, 83, 21, 36, 87, 70, 88, 88, 12, 58, 65, 39,
       87, 46, 88])

In [12]:
b = (a > 50)
b

array([False, False,  True,  True,  True, False,  True, False, False,
        True,  True,  True,  True, False,  True,  True, False,  True,
       False,  True])

In [13]:
type(b)

numpy.ndarray

In [14]:
unique, counts = np.unique(b, return_counts=True)
dict(zip(unique,counts))

{False: 8, True: 12}

In [15]:
a.shape[0]

20

In [16]:
from sklearn.datasets import load_iris
X_train, y_train = load_iris(return_X_y=True)

In [17]:
X_train.shape

(150, 4)

In [18]:
X_train = np.insert(X_train,0,1,axis=1)

In [19]:
X_train

array([[1. , 5.1, 3.5, 1.4, 0.2],
       [1. , 4.9, 3. , 1.4, 0.2],
       [1. , 4.7, 3.2, 1.3, 0.2],
       [1. , 4.6, 3.1, 1.5, 0.2],
       [1. , 5. , 3.6, 1.4, 0.2],
       [1. , 5.4, 3.9, 1.7, 0.4],
       [1. , 4.6, 3.4, 1.4, 0.3],
       [1. , 5. , 3.4, 1.5, 0.2],
       [1. , 4.4, 2.9, 1.4, 0.2],
       [1. , 4.9, 3.1, 1.5, 0.1],
       [1. , 5.4, 3.7, 1.5, 0.2],
       [1. , 4.8, 3.4, 1.6, 0.2],
       [1. , 4.8, 3. , 1.4, 0.1],
       [1. , 4.3, 3. , 1.1, 0.1],
       [1. , 5.8, 4. , 1.2, 0.2],
       [1. , 5.7, 4.4, 1.5, 0.4],
       [1. , 5.4, 3.9, 1.3, 0.4],
       [1. , 5.1, 3.5, 1.4, 0.3],
       [1. , 5.7, 3.8, 1.7, 0.3],
       [1. , 5.1, 3.8, 1.5, 0.3],
       [1. , 5.4, 3.4, 1.7, 0.2],
       [1. , 5.1, 3.7, 1.5, 0.4],
       [1. , 4.6, 3.6, 1. , 0.2],
       [1. , 5.1, 3.3, 1.7, 0.5],
       [1. , 4.8, 3.4, 1.9, 0.2],
       [1. , 5. , 3. , 1.6, 0.2],
       [1. , 5. , 3.4, 1.6, 0.4],
       [1. , 5.2, 3.5, 1.5, 0.2],
       [1. , 5.2, 3.4, 1.4, 0.2],
       [1. , 4

In [20]:
for index, data in enumerate(X_train):
    print(index)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149


In [21]:
np.sign(1.4)

1.0

In [22]:
len(X_train)

150